language: cpp

os:
  - linux

# Use Ubuntu 18.04 LTS (Bionic) as the Linux testing environment.
dist: bionic
sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - ocl-open-100

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - llvm-10-tools
      - llvm-10-dev
      - libclang-10-dev

install:
  - wget https://github.com/KhronosGroup/SPIRV-LLVM-Translator/releases/download/dev-build/SPIRV-LLVM-Translator-dev-build-linux-Release.zip -O /tmp/SPIRV-LLVM-Translator-dev-build-linux-${BUILD_TYPE}.zip
  - unzip /tmp/SPIRV-LLVM-Translator-dev-build-linux-${BUILD_TYPE}.zip -d spirv-llvm-translator
# This is a work-around for a "wrong" dependency between libclang-10-dev and
# libclang-cpp10-dev packages from apt.llv.org. Normally, we should just
# install them both, as it is done on the master(ocl-open-110) branch. But for
# some reason (a bug?) they remove each other when being installed via apt get.
# Basically, all we need from libclang-cpp10-dev is the symlink below. Without
# this symlink linker can't find libclang-cpp.so.10.
  - sudo ln -s ${TRAVIS_ROOT}/usr/lib/llvm-10/lib/libclang-cpp.so.10 ${TRAVIS_ROOT}/usr/lib/llvm-10/lib/libclang-cpp.so

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLLVM_NO_DEAD_STRIP=ON -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF -DSPIRV_TRANSLATOR_DIR=./spirv-llvm-translator -DCMAKE_INSTALL_PREFIX=./install ..
  - make install
