language: cpp

os:
  - linux

# Use Ubuntu 16.04 LTS (Xenial) as the Linux testing environment.
dist: xenial
sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - ocl-open-70
    - ocl-open-80

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - llvm-8-tools
      - llvm-8-dev
      - libclang-8-dev

install:
  - git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git -b llvm_release_80 spirv-llvm-translator
  - cd spirv-llvm-translator
  - for patch in `ls ../patches/spirv/*.patch`; do echo $patch; git apply -v $patch; done
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=./install -DBUILD_SHARED_LIBS=ON -DLLVM_BUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make -j`nproc` && make install
  - cd ../../

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLLVM_NO_DEAD_STRIP=ON -DLLVMSPIRV_INCLUDED_IN_LLVM=OFF -DSPIRV_TRANSLATOR_DIR=./spirv-llvm-translator -DCMAKE_INSTALL_PREFIX=./install ..
  - make install
